PTS integrity check crashing with nil pts fix
membraneframework/membrane_aac_fdk_plugin pull request #58
Opened 2024-04-15 22:43 UTC by bartkrak

solves: https://github.com/membraneframework/membrane_core/issues/791

2024-04-16 09:08 UTC, FelonEkonom requested changes
Changes are OK. Add test checking, if encoder can handle `nil` timestamps.

2024-04-17 10:28 UTC, FelonEkonom approved these changes

2024-04-17 12:47 UTC, varsill approved these changes

2024-04-17 12:47 UTC, varsill commented on test/membrane_element_fdk_aac/pts_test.exs
> +  use ExUnit.Case
How about?
```suggestion
  use ExUnit.Case, async: true
```

2024-04-17 13:27 UTC, merged